Repository retaildevcrews/ngsa-app, pull requests merged in 2021-06, with the labels that each got.

#38 Matching burst header to expected format
  Ngsa.App.csproj
  src/Controllers/HealthzController.cs
  src/Core/CpuCounter.cs
  src/Handlers/VersionExtension.cs
Labels: CustomerFeedback, InternalFeedback

#39 Abassey readme
  README.md
Labels: Documentation

#43 Add PR Action to Validate Container Will Run for ngsa-app repo
  .github/workflows/ngsa-pr.yaml
Labels: Bug

#44 Add LodeRunner test to ngsa-app C# CI/CD on Pull Request
  .github/workflows/ngsa-pr.yaml
  .github/workflows/ngsa.yaml
Labels: CI/CD
