Repository retaildevcrews/ngsa-app, pull requests merged in 2021-08, with the labels that each got.

#46 Added autogitops workflow
  .github/workflows/ngsa.yaml
  autogitops/autogitops.json
  autogitops/ngsa-preprod.yaml
Labels: CI/CD

#48 Benchmark Controller Return type
  src/Controllers/BenchmarkController.cs
Labels: Bug

#51 Update cosmos key to support upsert operations
  .github/workflows/ngsa-pr.yaml
Labels: Bug

#62 Updated ngsa workflow logic to run tests during schedule
  .github/workflows/ngsa.yaml
Labels: Bug, CI/CD

#63 update version for release
  Ngsa.App.csproj
Labels: Release, ngsa-csharp

#64 Removed Assembly and File version proj settings
  Ngsa.App.csproj
Labels: ngsa-csharp
