Repository retaildevcrews/ngsa-app, pull requests merged in 2022-04, with the labels that each got.

#96 Updated README to include instructions to open with codespaces
  Ngsa.App.csproj
  README.md
Labels: CI/CD, Documentation, size: S

#98 Updated README to include restrictions for ngsa-memory template
  README.md
  autogitops/dev/ngsa-memory.yaml
Labels: Bug, size: S, CI-CD

#97 Use retaildevcrews v0.3.0 image for autogitops
  .github/workflows/ngsa.yaml
Labels: CI/CD, CI-CD
