Repository retaildevcrews/ngsa-app, pull requests merged in 2022-08, with the labels that each got.

#122 log exception using ToString() instead of just the message property to ensure all details make it to logs
  .vscode/tasks.json
  src/NgsaLogger/NgsaLogger.cs
Labels: ngsa-csharp

#123 Added --quiet and --compact arguments to Checkov Scan task
  .vscode/tasks.json
Labels: Bug, CI/CD, ngsa-csharp

#124 Remove app specific burst metrics logic - #916
  README.md
  kitt-service.yml
  src/Controllers/HealthzController.cs
  src/Core/BurstMetricsService.cs
  src/Core/CommandLine.cs
  src/Core/Config.cs
  src/Handlers/VersionExtension.cs
  src/HealthChecks/IetfResponseWriter.cs
Labels: Bug, Documentation, size: M

#125 Fix vulnerabilities discovered in Grype
  .github/workflows/ngsa-pr.yaml
  .github/workflows/ngsa.yaml
  Makefile
  Ngsa.App.csproj
Labels: Bug, size: S

#126 dev: Update app deployments for improved resiliency
  autogitops/dev/ngsa-cosmos.yaml
Labels: DevOps

#127 preprod: Update app deployments for improved resiliency
  autogitops/preprod/ngsa-cosmos.yaml
Labels: DevOps
