Repository retaildevcrews/ngsa-app, pull requests merged in 2022-07, with the labels that each got.

#114 Added Check for CRLF line endings
  .github/workflows/crlf-check.yaml
  README.md
Labels: CI/CD, Enhancement, DevOps

#115 added dockerfile checkov, skip statements
  .devcontainer/Dockerfile
  .github/workflows/checkov-docker.yml
  Dockerfile
Labels: CI-CD, DevOps

#118 Added Grype image vulnerability scanner
  .github/workflows/ngsa-pr.yaml
  .github/workflows/ngsa.yaml
Labels: size: S, CI-CD, DevOps

#120 Add Checkov VS code Task to Codespaces and populate a summary section.
  .gitignore
  .vscode/tasks.json
  README.md
Labels: Bug, CI/CD, DevOps
